2021-02-05 10:22:20,377 ERROR: Exception on /login [GET] [in /home/muhinyuzi/Desktop/Test/microblog/env/lib/python3.6/site-packages/flask/app.py:1892]
Traceback (most recent call last):
  File "/home/muhinyuzi/Desktop/Test/microblog/env/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/muhinyuzi/Desktop/Test/microblog/env/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/muhinyuzi/Desktop/Test/microblog/env/lib/python3.6/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/muhinyuzi/Desktop/Test/microblog/env/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/muhinyuzi/Desktop/Test/microblog/env/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/muhinyuzi/Desktop/Test/microblog/env/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/muhinyuzi/Desktop/Test/microblog/app/routes.py", line 80, in login
    return render_template('login.html', title=_('Sign In'), form=form)
  File "/home/muhinyuzi/Desktop/Test/microblog/env/lib/python3.6/site-packages/flask/templating.py", line 138, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/home/muhinyuzi/Desktop/Test/microblog/env/lib/python3.6/site-packages/jinja2/environment.py", line 930, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/home/muhinyuzi/Desktop/Test/microblog/env/lib/python3.6/site-packages/jinja2/environment.py", line 883, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/home/muhinyuzi/Desktop/Test/microblog/env/lib/python3.6/site-packages/jinja2/environment.py", line 857, in _load_template
    template = self.loader.load(self, name, globals)
  File "/home/muhinyuzi/Desktop/Test/microblog/env/lib/python3.6/site-packages/jinja2/loaders.py", line 127, in load
    code = environment.compile(source, name, filename)
  File "/home/muhinyuzi/Desktop/Test/microblog/env/lib/python3.6/site-packages/jinja2/environment.py", line 638, in compile
    self.handle_exception(source=source_hint)
  File "/home/muhinyuzi/Desktop/Test/microblog/env/lib/python3.6/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/muhinyuzi/Desktop/Test/microblog/env/lib/python3.6/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/home/muhinyuzi/Desktop/Test/microblog/app/templates/login.html", line 18, in template
    {% endblock %}
jinja2.exceptions.TemplateSyntaxError: Encountered unknown tag 'endblock'.
2021-02-05 10:26:14,655 INFO: Microblog startup [in /home/muhinyuzi/Desktop/Test/microblog/app/__init__.py:52]
2021-02-05 10:26:30,020 INFO: Microblog startup [in /home/muhinyuzi/Desktop/Test/microblog/app/__init__.py:52]
2021-02-05 10:27:00,010 INFO: Microblog startup [in /home/muhinyuzi/Desktop/Test/microblog/app/__init__.py:52]
2021-02-05 10:30:59,429 INFO: Microblog startup [in /home/muhinyuzi/Desktop/Test/microblog/app/__init__.py:52]
2021-02-05 11:10:20,931 INFO: Microblog startup [in /home/muhinyuzi/Desktop/Test/microblog/app/__init__.py:52]
2021-02-06 08:46:23,065 INFO: Microblog startup [in /home/muhinyuzi/Desktop/Test/microblog/app/__init__.py:52]
2021-02-06 09:51:40,406 INFO: Microblog startup [in /home/muhinyuzi/Desktop/Test/microblog/app/__init__.py:74]
2021-02-06 11:54:32,453 INFO: Microblog startup [in /home/muhinyuzi/Desktop/Test/microblog/app/__init__.py:78]
2021-02-06 11:55:01,620 ERROR: Exception on /search [GET] [in /home/muhinyuzi/Desktop/Test/microblog/env/lib/python3.6/site-packages/flask/app.py:1892]
Traceback (most recent call last):
  File "/home/muhinyuzi/Desktop/Test/microblog/env/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/muhinyuzi/Desktop/Test/microblog/env/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/muhinyuzi/Desktop/Test/microblog/env/lib/python3.6/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/muhinyuzi/Desktop/Test/microblog/env/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/muhinyuzi/Desktop/Test/microblog/env/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/muhinyuzi/Desktop/Test/microblog/env/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/muhinyuzi/Desktop/Test/microblog/env/lib/python3.6/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/muhinyuzi/Desktop/Test/microblog/app/main/routes.py", line 152, in search
    current_app.config['POSTS_PER_PAGE'])
  File "/home/muhinyuzi/Desktop/Test/microblog/app/models.py", line 15, in search
    ids, total = query_index(cls.__tablename__, expression, page, per_page)
  File "/home/muhinyuzi/Desktop/Test/microblog/app/search.py", line 22, in query_index
    'from': (page - 1) * per_page, 'size': per_page})
  File "/home/muhinyuzi/Desktop/Test/microblog/env/lib/python3.6/site-packages/elasticsearch/client/utils.py", line 152, in _wrapped
    return func(*args, params=params, headers=headers, **kwargs)
  File "/home/muhinyuzi/Desktop/Test/microblog/env/lib/python3.6/site-packages/elasticsearch/client/__init__.py", line 1663, in search
    body=body,
  File "/home/muhinyuzi/Desktop/Test/microblog/env/lib/python3.6/site-packages/elasticsearch/transport.py", line 392, in perform_request
    raise e
  File "/home/muhinyuzi/Desktop/Test/microblog/env/lib/python3.6/site-packages/elasticsearch/transport.py", line 365, in perform_request
    timeout=timeout,
  File "/home/muhinyuzi/Desktop/Test/microblog/env/lib/python3.6/site-packages/elasticsearch/connection/http_urllib3.py", line 269, in perform_request
    self._raise_error(response.status, raw_data)
  File "/home/muhinyuzi/Desktop/Test/microblog/env/lib/python3.6/site-packages/elasticsearch/connection/base.py", line 316, in _raise_error
    status_code, error_message, additional_info
elasticsearch.exceptions.NotFoundError: NotFoundError(404, 'index_not_found_exception', 'no such index [post]', post, index_or_alias)
2021-02-06 11:55:35,884 ERROR: Exception on /search [GET] [in /home/muhinyuzi/Desktop/Test/microblog/env/lib/python3.6/site-packages/flask/app.py:1892]
Traceback (most recent call last):
  File "/home/muhinyuzi/Desktop/Test/microblog/env/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/muhinyuzi/Desktop/Test/microblog/env/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/muhinyuzi/Desktop/Test/microblog/env/lib/python3.6/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/muhinyuzi/Desktop/Test/microblog/env/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/muhinyuzi/Desktop/Test/microblog/env/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/muhinyuzi/Desktop/Test/microblog/env/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/muhinyuzi/Desktop/Test/microblog/env/lib/python3.6/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/muhinyuzi/Desktop/Test/microblog/app/main/routes.py", line 152, in search
    current_app.config['POSTS_PER_PAGE'])
  File "/home/muhinyuzi/Desktop/Test/microblog/app/models.py", line 15, in search
    ids, total = query_index(cls.__tablename__, expression, page, per_page)
  File "/home/muhinyuzi/Desktop/Test/microblog/app/search.py", line 22, in query_index
    'from': (page - 1) * per_page, 'size': per_page})
  File "/home/muhinyuzi/Desktop/Test/microblog/env/lib/python3.6/site-packages/elasticsearch/client/utils.py", line 152, in _wrapped
    return func(*args, params=params, headers=headers, **kwargs)
  File "/home/muhinyuzi/Desktop/Test/microblog/env/lib/python3.6/site-packages/elasticsearch/client/__init__.py", line 1663, in search
    body=body,
  File "/home/muhinyuzi/Desktop/Test/microblog/env/lib/python3.6/site-packages/elasticsearch/transport.py", line 392, in perform_request
    raise e
  File "/home/muhinyuzi/Desktop/Test/microblog/env/lib/python3.6/site-packages/elasticsearch/transport.py", line 365, in perform_request
    timeout=timeout,
  File "/home/muhinyuzi/Desktop/Test/microblog/env/lib/python3.6/site-packages/elasticsearch/connection/http_urllib3.py", line 269, in perform_request
    self._raise_error(response.status, raw_data)
  File "/home/muhinyuzi/Desktop/Test/microblog/env/lib/python3.6/site-packages/elasticsearch/connection/base.py", line 316, in _raise_error
    status_code, error_message, additional_info
elasticsearch.exceptions.NotFoundError: NotFoundError(404, 'index_not_found_exception', 'no such index [post]', post, index_or_alias)
2021-02-06 12:02:10,077 INFO: Microblog startup [in /home/muhinyuzi/Desktop/Test/microblog/app/__init__.py:78]
